name: Linux Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Linux Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Pulling the source
        uses: actions/checkout@v2
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Installing LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Building the game
        run: |
          haxelib run lime build linux -clean
      - name: Tar files
        run: tar -zcvf CodenameEngine.tar.gz -C export/release/linux/bin .
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: re mayhem
          path: CodenameEngine.tar.gz
