name: Mac OS Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Mac OS Build
    permissions: write-all
    runs-on: macos-13
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v2
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Building the game
        run: |
          haxelib run lime build mac -clean
      - name: Tar files
        run: tar -zcvf CodenameEngine.tar.gz -C export/release/macos/bin .
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: re mayhem
          path: CodenameEngine.tar.gz
